services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - /app
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
    command: >
      bash -c "
      aerich upgrade &&
      app/main.py
      "
    ports:
      - "8000:8000"

  db:
    image:
      postgres:16
    container_name: tg-profile-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:

